export const REGISTRATION_STATUS = {
  PENDING: "PENDING",
  PAID: "PAID",
  CANCELLED: "CANCELLED",
  EXPIRED: "EXPIRED",
};

export const REGISTRATION_STATUSES = Object.values(REGISTRATION_STATUS);
