export const NOTIFICATION_JOBS = {
  ORDER_CONFIRMED: "ORDER_CONFIRMED",
  ORDER_STATUS_UPDATED: "ORDER_STATUS_UPDATED",
  REGISTRATION_CONFIRMED: "REGISTRATION_CONFIRMED",
  WELCOME: "WELCOME",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  GROUP_CREATED: "GROUP_CREATED",
};
